CreateDAO
KNJPJATK/CZ_ZAAW_PROJ pull request #10
Opened 2016-12-01 15:44 UTC by wadosms

#1 Creted Answer in package model
#2 Implemented Question in package model
#3 Implemented QuestionDAO
#4 Add method executeUpdate
#5 Add class AnswerDAO, but is not implemented
#6 Implemented try with resources in method getUserByUsername

2016-12-06 20:35 UTC, s13302 commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +        if (!rs.next()) {
Czy metoda o podobnym działaniu nie jest odziedziczona z BaseDAO?

2016-12-06 20:35 UTC, s13302 commented on src/main/java/pl/knpj/servlet/model/Answer.java
> +public class Answer {
@domino2608 Co sądzisz o dodaniu stałego statycznego pola z nazwą tabeli?

2016-12-06 20:53 UTC, domino2608 requested changes

2016-12-06 20:53 UTC, domino2608 commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +    private static final String GET_ANSWERS_SQL =
Why it is called forKey?

2016-12-06 20:53 UTC, domino2608 commented on src/main/java/pl/knpj/servlet/model/Question.java
> +    private String description;
Where are stored all answers to the question?
You have only correct answers but not all.

2016-12-06 20:53 UTC, domino2608 commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +        if (!rs.next()) {
To wyglada na stary pull request

2016-12-06 20:53 UTC, domino2608 commented on src/main/java/pl/knpj/servlet/model/Answer.java
> +public class Answer {
Myslalem ogolnie o stworzeniu oddzielnej klasy ktora bedzie przechowywala stale z nazwami tabel i kolumn ;)

2016-12-06 20:53 UTC, domino2608 commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +            e.printStackTrace();
Po obsluzeniu bledow powinnismy propagowac je wyzej - uzytkownik tez powinien wiedziec ze wystapil jakis blad

2016-12-06 20:53 UTC, domino2608 commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +    public boolean checkIfAlready(String title) throws SQLException{
check if already ale co?

2016-12-06 20:53 UTC, domino2608 commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +    public void deleteFromTable(String name) throws SQLException{
To wyczysci cala tabele z bazy.
Nazwa deleteFromTable w takim wypadku jest malo intuicyjna i bardzo mylaca

2016-12-06 20:53 UTC, domino2608 commented on src/main/java/pl/knpj/servlet/dao/AnswerDAO.java
> +
Why it is blank?

2016-12-06 20:58 UTC, domino2608 commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +        if (!rs.next()) {
Lub przynajmniej nie wszystko jest wrzucone

2016-12-06 20:59 UTC, domino2608 commented on src/main/java/pl/knpj/servlet/model/Answer.java
> +public class Answer {
@s13302 co myslisz?^^

2016-12-06 21:06 UTC, s13302 commented on src/main/java/pl/knpj/servlet/model/Answer.java
> +public class Answer {
Jest to jakieś rozwiązanie, ale chcesz żeby była to oddzielna klasa dla każdego POJO?

2016-12-06 21:16 UTC, domino2608 commented on src/main/java/pl/knpj/servlet/model/Answer.java
> +public class Answer {
To jest jedno rozwiazanie (dla kazdego pojo oddzielna klasa)
A drugim moze byc jedna klasa ze wszystkimi i np z klasami wewnetrznymi dla konkretnych pojo lub po prostu zwyklymi stalymi ;)

2016-12-07 09:17 UTC, wadosms commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +        if (!rs.next()) {
Dokładnie tak, to jest stary pull request, już to poprawiłem

2016-12-07 09:24 UTC, vadym-ai commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +    private static final String GET_ANSWERS_SQL =
Zakładałem ze tabela answer będę miała kolumnę forKey(foreign key) gdzie będę trzymała id question. Ale ponieważ koncepcja się zmieniła i mamy na to oddzielną relacje, to już to poprawiłem

2016-12-07 09:31 UTC, wadosms commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +    public boolean checkIfAlready(String title) throws SQLException{
zła nazwa. było by lepiej : checkIfQuestionAlreadyInDB ? nie jest zadługa?

2016-12-07 09:37 UTC, wadosms commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +    public void deleteFromTable(String name) throws SQLException{
Właśnie robiłem tą metodę dla siebie , kiedy testowałem swoje DAO, ale zdecydowałem się ją zostawić. ok, a nazwa deleteAllContentsOfTable może być?

2016-12-07 09:58 UTC, domino2608 commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +    private static final String GET_ANSWERS_SQL =
Ale forKey na nazwe kolumny jest raczej srednie
Wszystko powinienes nazywac tak aby od razu bylo wiadomo co to jest

2016-12-07 10:00 UTC, domino2608 commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +    public boolean checkIfAlready(String title) throws SQLException{
Nazwa powinna od razu mowic co dana metoda robi

2016-12-07 10:00 UTC, domino2608 commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +    public boolean checkIfAlready(String title) throws SQLException{
Moze checkIfAlreadyExists?

2016-12-07 10:01 UTC, domino2608 commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +    public void deleteFromTable(String name) throws SQLException{
Moze byc tez cos w stylu
deleteAllFromTable

2016-12-07 10:04 UTC, domino2608 commented
JavaDoc do wszystkich publicznych metod obowiazkowo! ;)

2016-12-07 10:04 UTC, wadosms commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +    public boolean checkIfAlready(String title) throws SQLException{
super)

2016-12-07 10:06 UTC, vadym-ai commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +    public void deleteFromTable(String name) throws SQLException{
ok

2016-12-07 10:36 UTC, s13302 commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +    public void deleteFromTable(String name) throws SQLException{
Ale czy ta metoda jest tak naprawdę potrzebna? Czy będzie kiedykolwiek użyta?

2016-12-07 10:39 UTC, s13302 requested changes
Stary PR i trochę go nie rozumiem

2016-12-07 10:39 UTC, s13302 commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +    public boolean checkIfAlready(String title) throws SQLException{
A jaki jest cel istnienia tej metody? A wydaje mi się, że jak już sprawdzać to po ID a nie tytule

2016-12-07 10:41 UTC, wadosms commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +    public void deleteFromTable(String name) throws SQLException{
generalnie nie, ale j.w. pisałem zrobiłem ją tylko dla testowania i nie chcilem ją w ogóle dodawać do commitu, ale zapomniałem ją skasować)

2016-12-07 10:43 UTC, wadosms commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +    public boolean checkIfAlready(String title) throws SQLException{
Sprawdzać czy istnieje pytanie z danym tytułem, jeżeli nie to dodajemy do DB.

2016-12-07 18:13 UTC, domino2608 commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +    public void deleteFromTable(String name) throws SQLException{
no to ja usunac skoro jest nie potrzebna

2016-12-07 18:16 UTC, domino2608 commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +    public boolean checkIfAlready(String title) throws SQLException{
Po tytule tez sie mozew przydac - jak bedziesz tworzyl nowe pytanie to nie bedziesz mial jeszcze id ;)

2016-12-07 20:56 UTC, wadosms commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +    public void deleteFromTable(String name) throws SQLException{
ok

2016-12-07 21:11 UTC, wadosms commented
zakładałem że kolekcja ma wszystkie odpowiedzi poprawne i błędne. skoro mamy tabele asocjacyjną w której trzymamy informacje która odpowiedz jest poprawna, to możemy dostać tą informacje.

2016-12-07 21:46 UTC, domino2608 commented
Czyli mowisz ze jezeli chcesz sprawdzic czy odpowiedz jest poprawna to musisz zrobic kolejne zapytanie do bazy danych?
Lepiej jest wczytac wszystko za jednym zamachem i miec dwie kolekcje: jedna do trzymania wszystkich odpowiedzi, druga aby trzymac tylko ta poprawna ;)

2016-12-07 22:26 UTC, wadosms commented
aha , no tak zgadza się) ja tylko się uczę ;)

2016-12-07 22:37 UTC, domino2608 commented
Jak my wszyscy ;)

2016-12-09 13:52 UTC, s13302 requested changes
Jest parę rzeczy do zmiany, to co opisał @domino2608 i ja

2016-12-09 13:52 UTC, s13302 commented on src/main/java/pl/knpj/servlet/dao/BaseDAO.java
> -
W Pull Request nie powinno być nie zmienionych plików czyli np. usunięcia lini

2016-12-09 13:52 UTC, s13302 commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +            Collection<Answer> correctAnswers = new HashSet<>();
Dlaczego HashSet? Nie widzę miejsca gdzie korzystałbyś z właściwości HashSet

2016-12-09 13:58 UTC, wadosms commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +            Collection<Answer> correctAnswers = new HashSet<>();
Ok) Wszystkie klasy DAO akurat w tej chwili poprawiam) lepiej ArrayLista uzyc?

2016-12-09 15:42 UTC, domino2608 commented
Jedna rzecz
Dlaczego tworzysz nowa metode do parsowania ResultSet?
Taka metoda jest juz w BaseDAO i trzeba ja przeslonic

2016-12-13 15:31 UTC, domino2608 reviewed
@s13302 co myslisz?
Otwieramy bramę do naszego raju?^^

2016-12-13 15:31 UTC, domino2608 commented on src/main/java/pl/knpj/servlet/model/Question.java
> +            Iterator iterator = answers.iterator();
Petla foreach?^^

2016-12-13 15:31 UTC, domino2608 commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +        while (iterator.hasNext()){
Nie latwiej petla foreach?

2016-12-13 15:31 UTC, domino2608 commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +        while (iterator.hasNext()) {
Nie latwiej petla for each?

2016-12-13 15:31 UTC, domino2608 commented on src/main/java/pl/knpj/servlet/dao/BaseDAO.java
> +
Add this exception to upper catch

2016-12-13 18:15 UTC, vadym-ai commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +        while (iterator.hasNext()) {
To juz jest poprawione

2016-12-13 18:15 UTC, wadosms commented on src/main/java/pl/knpj/servlet/model/Question.java
> +            Iterator iterator = answers.iterator();
Jest poprawione

2016-12-13 18:16 UTC, wadosms commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +        while (iterator.hasNext()){
Jest poprawione

2016-12-15 15:01 UTC, domino2608 approved these changes
Looks ok for me :)
@s13302 please confirm if everything is ok :)

2016-12-19 18:45 UTC, s13302 requested changes
Potrzebne jest kilka zmian

2016-12-19 18:45 UTC, s13302 commented on src/main/java/pl/knpj/servlet/dao/AnswerDAO.java
> +     */
Może adnotacja @Override ?

2016-12-19 18:45 UTC, s13302 commented on src/main/java/pl/knpj/servlet/dao/BaseDAO.java
>              throw e;
Dlaczego 2 razy jest łapany ten sam typ wyjątku? SQLException

2016-12-19 18:45 UTC, s13302 commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +    public boolean checkIfAlreadyExist(String title) throws SQLException, ClassNotFoundException{
Co alreadyExists? Nazwy metody nie mają ograniczeń więc śmiałoooo

2016-12-19 18:45 UTC, s13302 commented on src/main/java/pl/knpj/servlet/model/Answer.java
> +public class Answer {
implements Serializable

2016-12-19 18:45 UTC, s13302 commented on src/main/java/pl/knpj/servlet/model/Question.java
> +public class Question {
implements Serializable

2016-12-19 18:45 UTC, s13302 commented on src/main/java/pl/knpj/servlet/model/Question.java
> +    public String toString() {
CO TO JEST?!

2016-12-19 18:45 UTC, s13302 commented on src/main/java/pl/knpj/servlet/model/Answer.java
> +    public String toString() {
Nie rozumiem, tak jak niżej

2016-12-29 13:38 UTC, domino2608 requested changes
Zmien na szybko to co bylo w komentarzach i mergujemy ;)

2016-12-29 13:38 UTC, domino2608 commented on src/main/java/pl/knpj/servlet/model/Answer.java
> +    public String toString() {
Frankenstein :p
A tak serio to co w tym zlego?^^

2016-12-29 13:38 UTC, domino2608 commented on src/main/java/pl/knpj/servlet/dao/QuestionDAO.java
> +    public boolean checkIfAlreadyExist(String title) throws SQLException, ClassNotFoundException{
Moim zdaniem metoda mowi juz sama za siebie ;)
new QuestionDAO().checkIfAlreadyExists("ala ma kota")

2016-12-29 13:55 UTC, wadosms commented
oks, juz poprawiam)

2016-12-29 14:11 UTC, wadosms commented
metode checkIfAlreadyExists zmieniamy nazwe?
co jest nie tak z metoda toString?

2016-12-29 14:15 UTC, domino2608 commented
Mozesz zmienic na cos w stylu checkIfQuestionWithTitleExists(String title)
@s13302 co jest nie tak z toString?

2016-12-29 14:27 UTC, domino2608 commented
@s13302 jeszcze jakies findingi?

2016-12-30 06:08 UTC, s13302 commented on src/main/java/pl/knpj/servlet/model/Answer.java
> +    public String toString() {
Jeszcze nie napisałem, że jest coś złego i próbowałem zrozumieć, teraz rozumiem jaki jest sens tego rozwiązania i zadaję sobie inne pytanie:
Czy nie lepiej było wykorzystać questions.toString()?

2016-12-30 06:08 UTC, s13302 commented on src/main/java/pl/knpj/servlet/model/Question.java
> +    public String toString() {
I tu też?

2017-01-08 10:37 UTC, s13302 commented
Ja bym jeszcze prosil o zastosowanie adnotacji Override tam gdzie jest to potrzebne, w kodzie znalazlem jedno takie miejsce

2017-01-09 23:29 UTC, merged

2017-01-09 23:29 UTC, domino2608 commented
merged.
Please add this annotation and then make another pr.