Registration page
KNJPJATK/CZ_ZAAW_PROJ pull request #14
Opened 2016-12-10 10:31 UTC by Adam7domanski

Removed keys

2016-12-10 10:46 UTC, Adam7domanski commented
:D wiem wiem. gratulacje dla mnie za pomysłowość z tym pullem zawierającym klucz :/

2016-12-15 12:45 UTC, domino2608 requested changes
Please update your branch, there cannot be changes in files that you didn't touch.

2016-12-15 12:45 UTC, domino2608 commented on pom.xml
> +    <name>servlet Maven Webapp</name>
Nie aktualne repo :P

2016-12-15 12:45 UTC, domino2608 commented on src/main/webapp/WEB-INF/web.xml
> -		 version="3.1">
Nie powinno byc zmian bez zmian :P
Wchodza w rachube wciecia nowe linie i ogolnie zmiany struktury pliku bez faktycznej zmiany.

2016-12-15 17:35 UTC, closed without merging