Registration page
KNJPJATK/CZ_ZAAW_PROJ pull request #15
Opened 2016-12-15 17:37 UTC by Adam7domanski

Megred repos + added registration page

2016-12-16 07:13 UTC, domino2608 approved these changes
Dobra teraz to juz jakos wyglada ;)
Te dwie zmiany ci juz daruje ;)

@s13302 juz moze nie byc taki mily :P

2016-12-19 18:28 UTC, s13302 requested changes
Przede wszystkim brakuje frameworka do JS

2016-12-19 18:28 UTC, s13302 commented on src/main/resources/js/regValidation.js
> +
Framework potrzebny jak powietrze!

2016-12-19 18:28 UTC, s13302 commented on src/main/webapp/WEB-INF/web.xml
> -		 version="3.1">
Nie widzę potrzeby wprowadzania takiej zmiany,

2016-12-19 18:28 UTC, s13302 commented on src/main/webapp/register.html
> +    <title>Title</title>
Może zastosujmy ładniejszy tytuł

2016-12-19 18:28 UTC, s13302 commented on src/main/webapp/register.html
> +    <input id="username" type="text" name="username" placeholder="Name" onblur="Validate('username',1)">
Nazwa funkcji java script z wielkiej litery?

2016-12-19 18:28 UTC, s13302 commented on src/main/resources/js/regValidation.js
> +                if(field_value ==""|| field_value == null)
Refaktor potrzebny jak powietrze - to chyba powinny być metody (w sensie każdy case)

2016-12-19 18:28 UTC, s13302 commented on src/main/resources/js/regValidation.js
> +password.addEventListener('input', function()
Czy ta funkcjonlność jest potrzebna? @domino2608

2016-12-21 20:53 UTC, domino2608 commented on src/main/webapp/register.html
> +    <title>Title</title>
potwierdzam

2016-12-21 20:53 UTC, domino2608 commented on src/main/webapp/WEB-INF/web.xml
> -		 version="3.1">
wrecz jej nie powinno byc

2016-12-21 20:57 UTC, domino2608 commented on src/main/resources/js/regValidation.js
> +password.addEventListener('input', function()
as you wish :P

2016-12-21 20:58 UTC, domino2608 commented on src/main/resources/js/regValidation.js
> +
niech sie pomecza w czystym js XD

2017-01-09 23:41 UTC, domino2608 commented
Co z tymi zmianami?

2025-01-15 18:06 UTC, closed without merging