Maven extensions
KNJPJATK/CZ_ZAAW_PROJ pull request #5
Opened 2016-11-25 16:32 UTC by domino2608

Added maven plugins for generating mysql and postgres databases.

2016-11-26 11:24 UTC, s13302 requested changes
Jest źle.

2016-11-26 11:24 UTC, s13302 commented on pom.xml
> +            <groupId>mysql</groupId>
Czy ta zależność nie powinna być w profilu mysql?

2016-11-26 11:24 UTC, s13302 commented on pom.xml
> +        <db.mysql.baseUrl>jdbc:mysql://127.0.0.1:3306/</db.mysql.baseUrl>
To powinno być w oddzielnym profilu, zobacz jak ja zrobiłem - profil postgresql

2016-11-26 11:24 UTC, s13302 commented on pom.xml
> +        <db.postgres.baseUrl>jdbc:postgresql://localhost:5432/</db.postgres.baseUrl>
Nie idźmy tą drogą, w ten sposób będziemy mieli miljon propertisów dotyczących tego samego

2016-11-26 12:10 UTC, domino2608 commented on pom.xml
> +            <groupId>mysql</groupId>
Profil ma sluzyc do generowania ale w sumie mozna powrzucac dependency do odpowiednich profili

2016-11-26 12:10 UTC, domino2608 commented on pom.xml
> +        <db.postgres.baseUrl>jdbc:postgresql://localhost:5432/</db.postgres.baseUrl>
Ale z drugiej strony bedziemy mieli lepsza separacje ;)

2016-11-26 12:12 UTC, domino2608 commented on pom.xml
> +        <db.mysql.baseUrl>jdbc:mysql://127.0.0.1:3306/</db.mysql.baseUrl>
Mysle ze mozna property dotyczace mysql przerzucic do profilu bedzie lepiej ;)

2016-11-26 12:13 UTC, s13302 commented on pom.xml
> +        <db.mysql.baseUrl>jdbc:mysql://127.0.0.1:3306/</db.mysql.baseUrl>
Doskonale, pan ma zawsze rację, zrób tak :+1:

2016-11-26 12:13 UTC, domino2608 commented
Zajme sie zmianami dzisiaj po devfest ;)

2016-11-28 04:07 UTC, s13302 requested changes

2016-11-28 04:07 UTC, s13302 commented on src/main/examples/maven_settings_ex/settings.xml
> +                <db.password>postgres</db.password>
A czy db.url nie jest zależny od bazy danych? I czy dp-props to dobra nazwa?

2016-11-28 06:26 UTC, domino2608 commented on src/main/examples/maven_settings_ex/settings.xml
> +                <db.password>postgres</db.password>
Jak sama nazwa wskazuje to jest przyklad ustawien  mavena ktore dla kazdego moga byc inne

2016-11-28 06:29 UTC, s13302 commented on src/main/examples/maven_settings_ex/settings.xml
> +                <db.password>postgres</db.password>
db-props sugeruje, że są to Properties do bazy danych :-1:

2016-11-28 06:33 UTC, domino2608 commented on src/main/examples/maven_settings_ex/settings.xml
> +                <db.password>postgres</db.password>
To zmien ta nazwe jezeli ci nie pasuje :P

2016-11-28 06:34 UTC, s13302 commented on src/main/examples/maven_settings_ex/settings.xml
> +                <db.password>postgres</db.password>
To twój pull request

2016-11-28 06:35 UTC, domino2608 commented on src/main/examples/maven_settings_ex/settings.xml
> +                <db.password>postgres</db.password>
I ja mowie ze jest dobrze :P

2016-11-28 06:41 UTC, s13302 commented on src/main/examples/maven_settings_ex/settings.xml
> +                <db.password>postgres</db.password>
To po co dałeś mnie w reviewersach?

2016-11-28 06:43 UTC, domino2608 commented on src/main/examples/maven_settings_ex/settings.xml
> +                <db.password>postgres</db.password>
Zaczynam sie zastanawiac :P
Moze jak czepiasz sie nazwy to podaj jakbys ja zmienil a nie tylko mowil ze jest zle i tyle XD

2016-11-28 06:44 UTC, s13302 commented on src/main/examples/maven_settings_ex/settings.xml
> +                <db.password>postgres</db.password>
Liczę na Twoją kreatywność aczkolwiek zgodną ze standardami

2016-11-28 08:33 UTC, s13302 approved these changes

2016-11-28 12:23 UTC, merged